crocodic-studio/crudbooster

src/CRUDBoosterServiceProvider.php
src/controllers/AdminController.php
src/database/seeds/DatabaseSeeder.php
src/helpers/Helper.php
src/routes.php
src/views/default/form_body.blade.php
src/views/default/privileges.blade.php
src/views/header.blade.php
src/views/home.blade.php

AdminController bug dashboard statistic
Service Provider re arrange load helper
Add faker for cms_posts
Add new function RouteController alternate Route::Controller
Improve helper
Bug readonly fixed at form body
Bug register option at privilege
Remove spiner animation at Notification
Bug morris js load

Bug Fix & Improve

---

src/views/sidebar.blade.php

It says "List Privilege" instead of "List User"

"List User" Typo

---

src/assets/assets/jsoneditor/jsoneditor.min.js
src/controllers/ModulsController.php
src/views/default/type_components/json/asset.blade.php
src/views/default/type_components/json/component.blade.php
src/views/default/type_components/json/component_detail.blade.php
src/views/default/type_components/json/info.json
src/views/module_generator/step3.blade.php

addition of json editor in types : https://github.com/jdorn/json-editor
i also start modifing the way for managing the options in the future we can other type of fields like check box instead of textarea

Add json type

---

src/assets/assets/jsoneditor/jsoneditor.min.js
src/controllers/AdminController.php
src/controllers/ApiCustomController.php
src/controllers/CBController.php
src/controllers/ModulsController.php
src/controllers/SettingsController.php
src/helpers/CRUDBooster.php
src/laravel-filemanager/src/controllers/LfmController.php
src/laravel-filemanager/src/middleware/MultiUser.php
src/laravel-filemanager/src/views/script.blade.php
src/routes.php
src/views/api_documentation_public.blade.php
src/views/default/form.blade.php
src/views/default/form_body.blade.php
src/views/default/type_components/checkbox/component.blade.php
src/views/default/type_components/checkbox/component_detail.blade.php
src/views/default/type_components/child/component.blade.php
src/views/default/type_components/date/asset.blade.php
src/views/default/type_components/date/component.blade.php
src/views/default/type_components/json/asset.blade.php
src/views/default/type_components/json/component.blade.php
src/views/default/type_components/json/component_detail.blade.php
src/views/default/type_components/json/info.json
src/views/default/type_components/select/info.json
src/views/module_generator/step1.blade.php
src/views/module_generator/step3.blade.php
src/views/sidebar.blade.php

i added the possibility to have several database in crudbooster 
because i have a project split in several databases and it was needed to split in several crudbooster

Possibility to have several database

---

src/assets/assets/rtl.css
src/localization/ar/crudbooster.php
src/localization/en/crudbooster.php
src/views/admin_template.blade.php
src/views/footer.blade.php
src/views/header.blade.php
src/views/login.blade.php
src/views/sidebar.blade.php

add more support for ar trans and rtl view
also I added a rtl.css to fix some css styles for rtl langs

add more ar Lang trans

---

src/controllers/CBController.php
src/helpers/CRUDBooster.php
src/views/admin_template.blade.php

as the Inline Script , I add two variables : 
`load_css` , `style_css`
I wish you update the documentation 
thank you

allow to include css styles and css files

---

src/assets/assets/js/main.js
src/assets/assets/rtl.css
src/database/seeds/DatabaseSeeder.php
src/localization/ar/crudbooster.php
src/localization/en/crudbooster.php
src/views/admin_template_plugins.blade.php
src/views/default/index.blade.php

add phrases for notifications in `main.js` file ,
add phrases in Database Seeder for the `group_setting`

add more ar trans

---

src/helpers/CRUDBooster.php
src/localization/ar/crudbooster.php
src/localization/en/crudbooster.php
src/localization/pt_br/crudbooster.php
src/localization/tr/crudbooster.php
src/views/default/index.blade.php
src/views/default/table.blade.php
src/views/default/type_components/filemanager/component.blade.php

- table filter&sqrt langauage update
- filemanager langauage update
- Turkish langauage add
- en , ar, ... update

General langauage update(tr add)

---

src/controllers/CBController.php

more information link:
https://github.com/crocodic-studio/crudbooster/issues/255

Table insert/update null array fix

---

src/controllers/CBController.php

postEditSave function null array fix not working properly.
more information:
https://github.com/laravel/framework/issues/11452

null array fix

---

src/commands/CrudboosterInstallationCommand.php
src/commands/CrudboosterUpdateCommand.php
src/controllers/CBController.php
src/localization/en/crudbooster.php
src/views/components/action.blade.php

New parameters:
'usepopupbox' : true/false
'popup_title' : Title of the confirmation box
'popup_text' : 'Message to user on the confirmation',
'popup_type' : Icon to be diplayed, example  :warning,
'popup_showCancelButton' : true/false
'popup_confirmButtonColor' : Color of button Example: '#DD6B55',                 'popup_confirmButtonText' : Button text,
'popup_closeOnConfirm' : 'true/false'

Add a confirmation dialog box for Action Button In Grid Data

---

src/controllers/CBController.php

Exapmles Code:
START COLUMNS DO NOT REMOVE THIS LINE
$this->col = [];
$this->col[] = ["label"=>"Sıra","name"=>"order"];
$this->col[] = ["label"=>"Başlık","name"=>"title"];
$this->col[] = ["label"=>"Resim","name"=>"path","image"=>true];
$this->col[] = ["label"=>"Link","name"=>"link"];
$this->col[] =["label"=>"Konumu","name"=>"type_id","join"=>"app_variables,code_name","join_where"=>"master_code=10","join_id"=>"code"];

Table display Join where support Add (only Code Behind)

---

src/localization/ar/crudbooster.php
src/localization/en/crudbooster.php
src/localization/es/crudbooster.php
src/localization/id/crudbooster.php
src/localization/pt_br/crudbooster.php
src/localization/tr/crudbooster.php
src/views/default/type_components/datamodal/browser.blade.php
src/views/default/type_components/datamodal/component.blade.php
src/views/default/type_components/datamodal/info.json

-  DataModule link options
- Modal Cache problem fix
- Data table list header value options

datamodal typecompenents langauage update

---

src/configs/crudbooster.php
src/views/admin_template.blade.php

Allows the user to select from the AdminLTE layouts

Select admin layout

---

src/commands/CrudboosterInstallationCommand.php
src/commands/CrudboosterUpdateCommand.php
src/database/seeds/CBSeeder.php

Use CBSeeder instead of DatabaseSeeder

CrudBooster own seeder

---

src/database/migrations/2016_08_07_145904_add_table_cms_apicustom.php
src/database/migrations/2016_08_07_150834_add_table_cms_dashboard.php
src/database/migrations/2016_08_07_151210_add_table_cms_logs.php
src/database/migrations/2016_08_07_152014_add_table_cms_privileges.php
src/database/migrations/2016_08_07_152214_add_table_cms_privileges_roles.php
src/database/migrations/2016_08_07_152320_add_table_cms_settings.php
src/database/migrations/2016_08_07_152421_add_table_cms_users.php
src/database/migrations/2016_08_07_154624_add_table_cms_moduls.php
src/database/migrations/2016_08_20_125418_add_table_cms_notifications.php
src/database/migrations/2016_09_04_033706_add_table_cms_email_queues.php
src/database/migrations/2016_10_01_144826_add_table_apikey.php
src/database/migrations/2016_11_14_141657_create_cms_menus.php

Move all timestamps() at end of database

Move all timestamps() at end of database cols

---

src/helpers/CRUDBooster.php

Change deprecated list() method to pluck() for Laravel 5.3 and up

Fix API fucntionality

---

src/controllers/StatisticBuilderController.php

Fix that not allow  user to delete statistic modules

Fix that not allow user to delete statistic modules

---

src/views/admin_template.blade.php

Show import and export buttons only on Index pages.Hide them from edit,show and add pages.

Show import and export buttons only on Index pages

---

src/controllers/LogsController.php

Bulk action button enabled by default in Admin Logs page for fast deleting logs

Bulk action button enabled by default in Logs

---

src/views/default/type_components/datamodal/info.json

datamodal module page link fix

update datamodal fix

---

src/views/default/index.blade.php

html tag fix

---

src/views/setting.blade.php

Fix that datapicker doesnt show value in settings

Fix that datapicker doesnt show value in settings

---

src/views/default/type_components/filemanager/component.blade.php

filemanager compenents langauage Improvement
image delete confirm swal update

filemanager compenents langauage Improvement

---

src/assets/assets/js/main.js
src/views/default/type_components/money/asset.blade.php
src/views/default/type_components/money/component.blade.php
src/views/default/type_components/money/info.json

Add decimal points on money field

Add decimal points on money field

---

src/views/default/type_components/date/asset.blade.php
src/views/default/type_components/date/component.blade.php

Date field issue

---

src/views/default/type_components/money/asset.blade.php
src/views/default/type_components/money/component.blade.php

Patch for component template issue #470

Patch money field component issue

---

docs/en/how-custom-view-add.md
docs/en/how-to-custom-detail-view.md
docs/en/how-to-custom-edit-view.md

small typo in extending view from vendor

extend view

---

src/views/default/type_components/child/component.blade.php

Table Header in Modal not showing. Fresh Installation with Updated CB

datamodal_columns_alias ( not showing )

---

src/controllers/CBController.php

sample 
`$this->sub_module[] = ['label'=>'Değişkenler','path'=>'app_variables','parent_columns'=>'code','custom_parent_id'=>'code','foreign_key'=>'master_code','button_color'=>'info','button_icon'=>'fa fa-bars','showIf'=>"[master_code] == '999'"];`

Submodule Custom parent id support

---

src/controllers/ModulsController.php
src/database/migrations/2017_06_06_164501_add_deleted_at_cms_moduls.php

fix cms_moduls soft delete error

---

src/controllers/NotificationsController.php

- added hook_query_index to Notification control to only show current users notifications
- Updated getLatestJson to not pull deleted notifications

Update Notifications index and Json

---

src/controllers/SettingsController.php

Wrong path when uploading new file, Issue related #691

Update upload file path fix

---

src/views/default/type_components/date/component.blade.php

Previous Code was forcing to be read-only always. This change will make the date input read-only or not depending on the property 'readonly' as it was designed.

Fix Read-Only in Date Component

---

src/views/default/type_components/child/component.blade.php

I add the JS code to the file `src/views/default/type_components/child/component.blade.php`
to enable parent_select in child

add js code in component child

---

src/CRUDBoosterServiceProvider.php
src/configs/crudbooster.php
src/database/migrations/2017_08_18_111216_add_deleted_at_cms_notifications.php
src/routes.php
src/userfiles/controllers/AdminUsersController.php

fix logout error

---

src/localization/ar/crudbooster.php
src/localization/en/crudbooster.php
src/localization/es/crudbooster.php
src/localization/id/crudbooster.php
src/localization/pt_br/crudbooster.php
src/localization/tr/crudbooster.php
src/localization/zh-CN/crudbooster.php
src/views/default/type_components/select/component.blade.php

From PR #681

---

src/controllers/LogsController.php
src/controllers/ModulsController.php

I just change the table name from string `cms_users` to be dynamic from the config file 
with `config('crudbooster.USER_TABLE')`

change cms_users to config var

---

src/views/components/action.blade.php

Allows to create an action button with title and without label

Allows to create an action button with title and without label

---

docs/en/how-to-custom-index.md
src/controllers/AdminApiGeneratorController.php
src/controllers/AdminController.php
src/controllers/AdminFileManagerController.php
src/controllers/AdminModulesController.php
src/controllers/AdminPrivilegesController.php
src/controllers/AdminSettingsController.php
src/controllers/AdminStatisticBuilderController.php
src/controllers/ApiController.php
src/controllers/CBController.php
src/controllers/FileController.php
src/helpers/CRUDBooster.php
src/middlewares/CBBackend.php
src/middlewares/CBSuperadmin.php

This code can be much better than it is now
I have started with the most obvious ways

The most obvious possible refactors

---

src/views/sidebar.blade.php

I found this bug a bit annoying for user interface on sidebar menu when using "sidebar-mini" style

adjust collapsed sidebar menu 

---

composer.json

Automatic package discovery for laravel 5.5
There for no need to add service provider in app.php

Package discovery

---

src/controllers/AdminPrivilegesController.php

uncheck horizantal not save fix.

all authority is not recorded when it is not selected

---

src/controllers/AdminPrivilegesController.php

Reverts crocodic-studio/crudbooster#880

Revert "all authority is not recorded when it is not selected"

---

src/controllers/PrivilegesController.php

add whereNull('deleted_at')

---

src/views/default/type_components/child/component.blade.php

Form with master detail when detail had a selec2 field type was not working

Form with master detail when detail had a selec2 field type was not working

---

src/views/default/type_components/multitext/component.blade.php

multitext comp.  validation error fixed.

multitext comp.  validation error fixed.

---

src/views/statistic_builder/components/table.blade.php
src/views/statistic_builder/index.blade.php

add datatable to widget table in statistics and delete background black to scroll in statics

add datatable to widget table in statistics

---

docs/en/how-to-make-graded-module.md

showIf also works for sub modules, but It wasn't in the docs.

Added showIf to the sub module docs

---

src/views/default/type_components/upload/component.blade.php
src/views/default/type_components/upload/component_detail.blade.php
src/views/sidebar.blade.php

Images in the laravel-project/public folder can be seen while viewing details or editing a record. So, It's not mandatory to put your pictures into uploads folder, you can put it also in the public folder.

Solved issues #1122 and #1126

---

src/views/sidebar.blade.php

It had been solved but It still had a problem. With this, It is working perfectly.

Solved issue #1126

---

src/controllers/PrivilegesController.php

When edit privilege, the table show deleted modules.

add query condition deleted_at=null

---

src/controllers/CBController.php

I decided to add an or (||) in order to keep compatibility and don't having to change the documentation.

Fixed #1260

---

src/views/components/action.blade.php

Default target="_self".
So you can do:
```php
$this->addaction[] = ['label' => 'Resolución',
'url' => CRUDBooster::mainpath('resolucion/[id]'), 'icon' => 'fa fa-file-pdf-o',
'color' => 'info', 'target' => '_blank'];
```

Added target attribute to addaction.

---

src/views/default/type_components/date/component_detail.blade.php

With this, no default date is shown if there's no value.

Showing empty date instead of default date.

---

src/views/default/type_components/datetime/component_detail.blade.php

With this, no default DateTime is shown if there's no value.

Showing empty datetime instead of default datetime

---

src/views/default/type_components/child/component.blade.php

&fk_value=" + fk_value + "datatable_where="     WRONG
&fk_value=" + fk_value + "&datatable_where="    OK

Missing & in URL to Select Parent_Select in Child

---

src/views/admin_template.blade.php

Throws a countable error for PHP 7.2 and needs this to be fixed.

Fix for PHP 7.2

---

src/controllers/CBController.php
src/helpers/CB.php
src/helpers/CRUDBooster.php
src/views/default/type_components/select2/component.blade.php
src/views/default/type_components/select2/component_detail.blade.php
src/views/default/type_components/select2/info.json

The ability to display data from the reference table with arbitrary keys.

xSoulRootx patch 1

---

src/controllers/CBController.php
src/controllers/FileController.php
src/controllers/MenusController.php
src/helpers/CRUDBooster.php
src/views/admin_template.blade.php
src/views/login.blade.php

Updating an string without translation

 Update on admin_template.blade.php

---

src/controllers/CBController.php

Fix child form, on post blank data

Fix Error On Child Form

---

src/views/default/type_components/select/component.blade.php

So, you can do:
```php
$this->form[] = [
'label' => 'Fallo', 'name' => 'tipos_resoluciones_id', 'type' => 'select',
'validation' => 'required|exists:tipos_resoluciones,id',
'datatable' => 'tipos_resoluciones,nombre', 'datatable_format' => "id,' - ',nombre",
'datatable_order' => 'id,asc',
];
```

Added datatable_order to select form.

---

src/helpers/CRUDBooster.php
src/views/admin_template.blade.php

Refer Comment: https://github.com/crocodic-studio/crudbooster/issues/1433#issuecomment-507458499

Fixes to accommodate url changes and custom form title and icon to display correctly.

---

src/controllers/MenusController.php
src/controllers/StatisticBuilderController.php
src/middlewares/CBBackend.php
src/routes.php
src/views/statistic_builder/index.blade.php

Relate to issue [#1057](https://github.com/crocodic-studio/crudbooster/issues/1057) 
Solution , change mainpath to adminpath , in order to widgets load in every view.

bug fix for widgets at cms_statistics_builder

---

src/views/default/type_components/datetime/component.blade.php

Optimize the open function and fix a issue with two or more datetime component in the same form

Fix and optimize datatime

---

src/types/money/Money.php

Halo mas. Ada kesalahan penamaan variable

$precision -> $separator variable

---

src/views/sidebar.blade.php

replacing deprecated ends_with function so it compatible with laravel 6

replace deprecated ends_with function

---

src/database/seeds/CBSeeder.php

Comment or remove line `namespace Database\Seeders;`

Fix: Target class [CBSeeder] does not exist.

---

docs/en/form-datamodal.md
docs/en/how-to-make-a-child-form.md
src/controllers/CBController.php
src/views/default/type_components/child/component.blade.php
src/views/default/type_components/datamodal/component.blade.php

This makes possible to setup two parametres at the datamodal type and the child form with datamodal, so that the user can setup its own pagination and height for the modal.

datamodal height and datamodal pagination
