resources/views/admin/default/form.blade.php

mungkin utk merubah foreign key pada form_sub agar lebih dinamis tidak harus id_namatable. 
karna setau saya default laravel menggunakan **namatable_id** utk foreign key seperti **user_id**.
`$this->form_sub[] = array('Label' => 'Article', 'controller' => 'ArticleController', 'foreign_key' => 'category_id' );
`

add "foreign_key" (optional) key for form_sub.

---

src/controllers/CBController.php
src/helpers/CRUDBooster.php
src/views/default/index.blade.php

allow to add HTML code in the index list before and after the table.
its can be used to show some text (not alert) or some html codes or special links ... etc 
Example : 
I add two options : `pre_index_html` , `post_index_html` and its null by default , to be used in `cbInit()` like : 
```
$this->pre_index_html = "
<div style='margin: 5px; padding: 10px; border: solid 1px darkgrey'>
Quick status filter :
<select name=\"limit\" style=\"width: 200px;\" class=\"form-control input-sm\">
<option>status 1</option>
<option>status 2</option>
<option>status 3</option>
</select>
</div>
";
```
I hope you find it useful 
thank you .

allow html code in indexs

---

src/views/default/type_components/child/component.blade.php

This is a really small change, however I could not make hidden input works in child type without this code change. I will really appreciate if you can look at it and merge it to you repository. It will not create a label if the type of the input is hidden

Support Hidden Input in Child Type

---

src/views/default/type_components/select/component.blade.php

The default option "** Please select a [Label]" sometimes doesn't make sense, for example labels like "Employee,  Article, etc" it should be  "Please select an ...". This change, will let developers override default option by setting the 'default' property. If 'default' property is not set, it will default to the lang:text_prefix_option, as it is now.
Usage Example:
$this->form[] = [
'label'      => 'Assign To',
'name'       => 'assign_to',
'type'       => 'select',
'validation' => 'required',
'width'      => 'col-sm-4',
'default'    => 'Select Employee Name',
"dataquery"  => 'select id as value,name as label from cms_users',
];

Add Default Option for Select Type

---

src/views/default/type_components/child/component.blade.php
src/views/default/type_components/select/info.json

The current code is throwing an error when you trying to add a radio in a child form, since is trying to loop 'dataenum' before exploding it.This new code checks if 'dataenum' is explodable and if it is not it will create an array of the string so it will trim and loop with no errors.

Fix Child Radio Type Error

---

src/controllers/CBController.php

When you return false on "actionButtonSelected", it will display a custom notification and a custom message. If it returns something else than false it will works as it is now. 
Now, it always displays: "You have :action successfully !" with an "alert-success" notification 
Usage:
public function actionButtonSelected($id_selected, $button_name) {
// Set custom Message and Custom Alert Type
$this->alert = ['message' => 'Please choose at least one sale.', 'type' => 'danger'];
// Return false
return false;
}

Add error notification capability for ActionButtonSelected

---

src/views/default/type_components/child/component.blade.php

let say I have table product (parent) and productitems (child), both has name column.
when I want to edit the record of one product and save button pushed, name of the product will be discarded, because has same "name" input with child form.
the last column order value (child) will be post instead of parent.
i'm proposing to alter name in child form to 
`name='child-{{$col["name"]}}'`
since when child form 'Add To Table' button pushed only consider id/class and not name.
`value='"+$('#{{$name.$c["name"]}}').val()+"'`

change form name in child form to avoid conflict with parent form

---

.gitignore
src/views/api_generator.blade.php

Minor thing but it breaks API generation entirely if you're running under SSL.  Fixes the request to the CDN to depend on the protocol the CMS is using.

fixes codebreaking hardcoded protocols in api generation views

---

docs/en/how-to-put-custom-condition-grid-data.md
docs/en/how-to-validate-api-request.md
src/controllers/ApiController.php

This is tend to add custom pre-checking/validation before executing API if needed.
If checking not pass then set 
`$this->discard_api = true;`
and send the message
`$this->hook_api_message = 'Some message why not pass!';`

Add pre-checking for some custom validation if needed before execute API

---

docs/en/form-money.md
src/views/default/type_components/money/asset.blade.php

[![screenshot_20170912_221657.jpg](https://s26.postimg.org/py0184j6x/screenshot_20170912_221657.jpg)](https://postimg.org/image/yg9hcgpph/)
different money format for each form.
use 'priceformat_parameters' as array in form parameter.
ex. 
```php
$this->form[] = [... 'type'=>'money','priceformat_parameters' => ['prefix' => 'Rp. ', 'thousandsSeparator' => '.', 'centsSeparator' => ',', 'centsLimit' => 2] ...];
```
custom parameter list http://flaviosilveira.com/Jquery-Price-Format/

fix form type money parameter

---

src/views/sidebar.blade.php

When you have PHP 7.2 and create a menu, the problem appears in CRUDBooster v5.3 and v5.4

Solved issues: #1048 and #1077

---

src/routes.php

Added `->where('deleted_at', null)` for being able to use `php artisan route:list` after a module is deleted.

Fixed #1234

---

src/controllers/CBController.php

Because there are more than two levels, the URL parameters will be repeated, causing the correct parameters to be overwritten.
E.g
if this code 
`urlencode(Request::fullUrl())`
get value is 
`https://www.xxx.com/data?parent_table=table&return_url=http://www.xxx.com/list`,
you will find this problem.

change sub module url parameter sort to support greater than two levels

---

docs/en/how-to-make-graded-module.md

The right name is parent_columns_alias.
https://github.com/crocodic-studio/crudbooster/search?q=parent_columns_alias&unscoped_q=parent_columns_alias

custom_parent_alias doesn't exist for sub modules.

---

src/views/default/table.blade.php

The comparison operators like >, >=, <, >= and Between in filters where appearing just for datatypes INT, DOUBLE, FLOAT, DECIMAL, TIME. Added the datatypes SMALLINT, TINYINT, MEDIUMINT, BIGINT so the comparison operators appear also for these datatypes.
In case of BETWEEN operator, a "timepicker" class and "readonly" attribute were set for any datatype except DATE ones, so also numeric datatypes were forced with timepicker class and readonly, thus not being able to use the BETWEEN filter operator for numbers.

Filter form fixes for integers

---

src/controllers/CBController.php

Had an issue with Child Forms do not pickup the ID of the foreign KEY after insertion. The logic helps pickup the right ID under the user interaction.

Update CBController.php Direct Reference to ID for PHP 7

---

src/controllers/CBController.php

The insert column counts become offset in cases when you have zero values. Using "empty" failed in conditions when the field is not required. The insert query builder was set to insert the array, which must match column count.  Using "isset" prompts the business logic to gather the value regardless.

Update CBController, Support Post Values

---

src/commands/CrudboosterInstallationCommand.php

Laravel 7 upgraded Symphony from 4 to 5 and Process syntax changed.
New usage : 
```
$process = new Process(['ls', '-lsa']);
$process->run();
```

Fixed issue caused by the new syntax of Process constructor since Laravel 7.0

---

src/views/default/type_components/datamodal/browser.blade.php

Fix error `Call to undefined function str_limit()` when browse data child form
Replace `echo "<td>".str_limit(strip_tags($row->$col), 50)."</td>";` with `echo "<td>".Str::of(strip_tags($row->$col))->limit(50)."</td>";`
Laravel 7+

Fix: Call to undefined function str_limit()

---

src/views/default/form_detail.blade.php

ErrorException
Array and string offset access syntax with curly braces is deprecated
PHP 7.3
Laravel 7+
Crudbooster 5.5.*

Fix form_detail.blade.php
